global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "flink"
    dns_sd_configs:
      - names:
          - 'taskmanager'
        refresh_interval: 1s
        type: 'A'
        port: 9249
    metrics_path: /
  - job_name: "flink-job-manger"
    static_configs:
      - targets: ['jobmanager:9249', 'jobmanager:8082'] 
    metrics_path: /