image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Services + Bootstrap + Data
    init: |
      echo "🚀 Starting Docker containers..."
      docker-compose up -d

      echo "⏳ Waiting for PostgreSQL to be ready..."
      for i in {1..15}; do
        if psql -h localhost -p 5432 -U pguser -d pgdb -c '\q' 2>/dev/null; then
          echo "✅ PostgreSQL is ready!"
          break
        else
          echo "Attempt $i: PostgreSQL not ready yet"
          sleep 3
        fi
      done

      echo "📦 Running pg_bootstrap.sql to create sink target tables..."
      PGPASSWORD=pgpass psql -h localhost -p 5432 -U pguser -d pgdb < 02-simple-demos/capital_markets/market_data_enrichment/pg_bootstrap.sql

      echo "⏳ Waiting for RisingWave to be ready..."
      for i in {1..15}; do
        if psql -h localhost -p 4566 -U root -d dev -c '\q' 2>/dev/null; then
          echo "✅ RisingWave is ready!"
          break
        else
          echo "Attempt $i: RisingWave not ready yet"
          sleep 3
        fi
      done

      echo "📦 Running RisingWave bootstrap.sql..."
      psql -h localhost -p 4566 -U root -d dev < 02-simple-demos/capital_markets/market_data_enrichment/bootstrap.sql

      echo "🐍 Installing Python dependencies..."
      sudo apt-get update &&
      sudo apt-get install -y python3-pip &&
      pip3 install psycopg2-binary

      echo "🧪 Running data generator..."
      python3 ./02-simple-demos/capital_markets/market_data_enrichment/data_generator.py



ports:
  - port: 4566
    onOpen: ignore
  - port: 5691
    onOpen: ignore
  - port: 9092
    onOpen: ignore
  - port: 2181
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 8088
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
