image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Services + Bootstrap + Data
    init: |
      echo "🚀 Starting Docker containers..."
      docker-compose up -d

      echo "⏳ Waiting for PostgreSQL to be ready..."
      for i in {1..15}; do
        if psql -h localhost -p 5432 -U pguser -d pgdb -c '\q' 2>/dev/null; then
          echo "✅ PostgreSQL is ready!"
          break
        else
          echo "Attempt $i: PostgreSQL not ready yet"
          sleep 3
        fi
      done

      echo "⏳ Waiting for RisingWave to be ready..."
      for i in {1..15}; do
        if psql -h localhost -p 4566 -U root -d dev -c '\q' 2>/dev/null; then
          echo "✅ RisingWave is ready!"
          break
        else
          echo "Attempt $i: RisingWave not ready yet"
          sleep 3
        fi
      done

      echo "🐍 Installing Python + psycopg2..."
      sudo apt-get update
      sudo apt-get install -y python3-pip
      pip3 install psycopg2-binary

      echo "📁 Selected demo: ${DEMO_PATH}"

      if [ "$DEMO_PATH" = "02-simple-demos/capital_markets/market_data_enrichment" ]; then
        echo "⚙️ Bootstrapping Market Data Enrichment..."
        PGPASSWORD=pgpass psql -h localhost -p 5432 -U pguser -d pgdb < ${DEMO_PATH}/pg_bootstrap.sql
        psql -h localhost -p 4566 -U root -d dev < ${DEMO_PATH}/bootstrap.sql
        python3 ${DEMO_PATH}/data_generator.py

      elif [ "$DEMO_PATH" = "02-simple-demos/capital_markets/market_surveillance" ]; then
        echo "⚙️ Bootstrapping Market Surveillance..."
        PGPASSWORD=pgpass psql -h localhost -p 5432 -U pguser -d pgdb < ${DEMO_PATH}/pg_bootstrap.sql
        psql -h localhost -p 4566 -U root -d dev < ${DEMO_PATH}/bootstrap.sql
        python3 ${DEMO_PATH}/data_generator.py

      elif [ "$DEMO_PATH" = "02-simple-demos/capital_markets/market_anomaly_detection" ]; then
        echo "⚙️ Bootstrapping Market Anomaly Detection..."
        PGPASSWORD=pgpass psql -h localhost -p 5432 -U pguser -d pgdb < ${DEMO_PATH}/pg_bootstrap.sql
        psql -h localhost -p 4566 -U root -d dev < ${DEMO_PATH}/bootstrap.sql
        python3 ${DEMO_PATH}/data_generator.py

      else
        echo "⚠️ No valid DEMO_PATH set. Skipping demo bootstrap."
      fi

ports:
  - port: 8088
    onOpen: open-preview
  - port: 4566
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 9092
    onOpen: ignore
  - port: 2181
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
