tasks:
  - name: Start Services + Bootstrap
    init: |
      docker-compose up -d

      # Wait for RisingWave
      for i in {1..15}; do
        if psql -h localhost -p 4566 -U root -d dev -c '\q' 2>/dev/null; then break; else sleep 3; fi
      done

      # Bootstrap RisingWave
      psql -h localhost -p 4566 -U root -d dev < 02-simple-demos/capital_markets/market_data_enrichment/bootstrap.sql

      # Wait for PostgreSQL
      for i in {1..15}; do
        if psql -h localhost -p 5432 -U pguser -d pgdb -c '\q' 2>/dev/null; then break; else sleep 3; fi
      done

      # Bootstrap PostgreSQL sink targets
      PGPASSWORD=pgpass psql -h localhost -p 5432 -U pguser -d pgdb < 02-simple-demos/capital_markets/market_data_enrichment/pg_bootstrap.sql
