image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Environment
    init: |
      docker-compose up -d
      echo "⏳ Waiting for RisingWave to be ready..."

      for i in {1..10}; do
        if psql -h localhost -p 4567 -U root -d dev -c '\q' 2>/dev/null; then
          echo "✅ RisingWave is ready!"
          break
        else
          echo "⏳ Attempt $i: RisingWave not ready yet"
          sleep 3
        fi
      done

      echo "▶ Running bootstrap SQL..."
      psql -h localhost -p 4567 -U root -d dev < bootstrap.sql || echo "⚠️ Failed to run bootstrap.sql, continuing anyway..."

ports:
  - port: 4567
    onOpen: ignore
  - port: 5691
    onOpen: ignore
  - port: 9000
    onOpen: open-preview
  - port: 9092
    onOpen: ignore
  - port: 2181
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
