image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Services
    init: |
      docker-compose up -d
      echo "Waiting for RisingWave to be ready..."
      for i in {1..10}; do
        if psql -h localhost -p 4566 -U root -d dev -c '\q' 2>/dev/null; then
          echo "RisingWave is ready!"
          break
        else
          echo "Attempt $i: RisingWave not ready yet"
          sleep 3
        fi
      done

ports:
  - port: 4566
    onOpen: ignore
  - port: 5691
    onOpen: ignore
  - port: 9092
    onOpen: ignore
  - port: 2181
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 8088
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
