image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Environment
    init: |
      docker-compose up -d
      echo "⏳ Waiting for RisingWave to be ready..."

      # Try connecting up to 10 times, waiting 3s each time
      for i in {1..10}; do
        if psql -h localhost -p 4567 -U root -d dev -c '\q' 2>/dev/null; then
          echo "✅ RisingWave is ready!"
          break
        else
          echo "⏳ Attempt $i: RisingWave not ready yet"
          sleep 3
        fi
      done

      echo "▶ Running bootstrap SQL..."
      psql -h localhost -p 4567 -U root -d dev < bootstrap.sql

ports: 
  - port: 4567
    onOpen: ignore
  - port: 8083
    onOpen: ignore
  - port: 5691
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
