version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka:3.4.0-debian-11-r0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"

  risingwave:
    image: ghcr.io/risingwavelabs/risingwave:latest
    container_name: risingwave
    command: playground
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "4566:4566"
      - "5691:5691"

    superset:
      image: apache/superset:latest
      container_name: superset
      environment:
        - SUPERSET_LOAD_EXAMPLES=yes
        - ADMIN_USERNAME=admin
        - ADMIN_PASSWORD=admin
        - ADMIN_FIRST_NAME=Admin
        - ADMIN_LAST_NAME=User
        - ADMIN_EMAIL=admin@example.com
      ports:
        - "8088:8088"
      depends_on:
        - risingwave
        - postgres
      extra_hosts:
        - "host.docker.internal:host-gateway"